name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Review this pull request carefully:

            PR Title: ${{ github.event.pull_request.title }}
            PR Description: ${{ github.event.pull_request.body }}

            Please:
            1. Review all code changes for quality, bugs, and best practices
            2. Check if the changes align with the PR description
            3. Verify workflows are properly configured
            4. Look for security issues or credential leaks
            5. Suggest improvements if needed

            If the PR looks good and passes all checks, approve it.
            If there are issues, request changes with clear feedback.
          comment_on_pr: true
