name: Cross-Repo Notify (By Commit)

on:
  schedule:
    # Run every 8 hours
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  notify-downstream:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to analyze changes

      - name: Analyze workflow changes
        id: changes
        run: |
          # Find changes in .github/workflows/ from last 8 hours
          SINCE="8 hours ago"

          # Get commits that modified workflows
          COMMITS=$(git log --since="$SINCE" --pretty=format:"%H" -- .github/workflows/)

          if [ -z "$COMMITS" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No workflow changes in the last 8 hours"
            exit 0
          fi

          echo "has_changes=true" >> $GITHUB_OUTPUT

          # Save commit list for Claude analysis
          echo "$COMMITS" > /tmp/commits.txt

          # Generate files changed summary
          echo "## Modified Workflow Files" > /tmp/files-changed.txt
          git log --since="$SINCE" --name-only --pretty=format: -- .github/workflows/ | sort -u | grep -v '^$' >> /tmp/files-changed.txt

          # For each commit, get the full diff
          mkdir -p /tmp/commit-diffs
          for commit in $COMMITS; do
            {
              echo "=== COMMIT: $commit ==="
              echo "Subject: $(git log -1 --pretty=format:'%s' $commit)"
              echo "Author: $(git log -1 --pretty=format:'%an <%ae>' $commit)"
              echo "Date: $(git log -1 --pretty=format:'%ai' $commit)"
              echo ""
              echo "Full commit message:"
              git log -1 --pretty=format:'%B' $commit
              echo ""
              echo "Diff:"
              git show $commit -- .github/workflows/
              echo ""
              echo "=== END COMMIT ==="
              echo ""
            } > /tmp/commit-diffs/${commit}.txt
          done

          # Combine all diffs for Claude
          cat /tmp/commit-diffs/*.txt > /tmp/all-diffs.txt
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Python
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.changes.outputs.has_changes == 'true'
        run: pip install anthropic

      - name: Analyze changes with Claude
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          chmod +x scripts/analyze-workflow-changes.py
          python scripts/analyze-workflow-changes.py by-commit /tmp/all-diffs.txt /tmp/changelog.md
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Create issue in issue-dump
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
        run: |
          TITLE="Workflow changes in jamiew/clactions ($(date -u '+%Y-%m-%d %H:%M UTC'))"

          # Build issue body with changelog + footer
          {
            cat /tmp/changelog.md
            echo ""
            echo "---"
            echo ""
            echo "@claude Please review these workflow changes and update any affected documentation, API clients, or downstream systems that may be impacted."
            echo ""
            echo "**Repository:** jamiew/clactions"
            echo "**Analysis method:** Per-commit (AI-analyzed)"
            echo ""
            echo "**Links:**"
            echo "- [View workflow directory](https://github.com/jamiew/clactions/tree/main/.github/workflows)"
            echo "- [Recent commits](https://github.com/jamiew/clactions/commits/main/.github/workflows)"
            echo "- [This workflow run](https://github.com/jamiew/clactions/actions/runs/${{ github.run_id }})"
          } > /tmp/issue-body.md

          gh issue create \
            --repo jamiew/issue-dump \
            --title "$TITLE" \
            --body-file /tmp/issue-body.md
