name: Cross-Repo Notify (By Commit)

on:
  schedule:
    # Run every 8 hours
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notify-downstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze and notify
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_args: |
            --allowedTools "Bash(git:*),Bash(gh:*),Bash(date:*),Bash(cat:*),Bash(mkdir:*),Bash(echo:*),Read,Write"
          prompt: |
            Analyze workflow changes from the last 8 hours and create an issue on jamiew/issue-dump.

            Tasks:
            1. Find commits that modified .github/workflows/ in the last 8 hours:
               ```bash
               git log --since="8 hours ago" --pretty=format:"%H" -- .github/workflows/
               ```

            2. If no changes found, exit successfully with a message.

            3. For each commit found, analyze:
               - Commit hash, subject, author, date
               - Full commit message
               - Diff showing what changed in workflow files

            4. Write a comprehensive changelog to changelog.md with this structure:

               ## Summary
               [2-3 sentence overview of what changed overall - be specific about themes]

               ## Key Changes
               - [Bullet point for most important change]
               - [Another important change]
               - [3-5 key changes total - focus on impact]

               ## Changes by Commit

               For each commit:
               ### [`short-hash`](https://github.com/jamiew/clactions/commit/FULL_HASH) - Subject
               *Author, Date*

               **Summary:** [1-2 sentences describing what this commit does]

               **Changes:**
               - [Specific change 1 - mention file names, what functionality changed]
               - [Specific change 2 - be concrete about schedules, permissions, jobs, etc.]
               - [etc]

               <details><summary>Full commit message</summary>

               ```
               [Include full commit message if it provides useful context beyond subject]
               ```
               </details>

               ---

            5. Create the issue on jamiew/issue-dump using gh CLI:
               ```bash
               export GH_TOKEN="${{ secrets.CROSS_REPO_PAT }}"
               gh issue create \
                 --repo jamiew/issue-dump \
                 --title "Workflow changes in jamiew/clactions ($(date -u '+%Y-%m-%d %H:%M UTC'))" \
                 --body "$(cat changelog.md)

               ---

               @claude Please review these workflow changes and update any affected documentation, API clients, or downstream systems that may be impacted.

               **Repository:** jamiew/clactions
               **Analysis method:** Per-commit (AI-analyzed)

               **Links:**
               - [View workflow directory](https://github.com/jamiew/clactions/tree/main/.github/workflows)
               - [Recent commits](https://github.com/jamiew/clactions/commits/main/.github/workflows)
               - [This workflow run](https://github.com/jamiew/clactions/actions/runs/${{ github.run_id }})"
               ```

            Important:
            - Be specific about what changed: schedules (cron), permissions, new jobs, new steps, renamed workflows
            - Focus on downstream impact - what might break or need updating?
            - Highlight breaking changes or significant behavioral changes
            - Don't include full diffs in the issue, just your analysis
            - If there are patterns (e.g. multiple workflows got same fix), call that out in summary
