name: Cross-Repo Notify (DEPRECATED)

# DEPRECATED: This workflow has been replaced by two better versions:
# - cross-repo-notify-by-commit.yml - Analyzes each commit individually
# - cross-repo-notify-unified.yml - Holistic analysis of all changes
#
# This version is kept for reference but disabled.

on:
  # Disabled - use new workflows instead
  # schedule:
  #   - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  notify-downstream:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to analyze changes

      - name: Analyze workflow changes
        id: changes
        run: |
          # Find changes in .github/workflows/ from last 8 hours, excluding data/
          SINCE="8 hours ago"

          # Get commits that modified workflows
          COMMITS=$(git log --since="$SINCE" --pretty=format:"%H" -- .github/workflows/)

          if [ -z "$COMMITS" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No workflow changes in the last 8 hours"
            exit 0
          fi

          echo "has_changes=true" >> $GITHUB_OUTPUT

          # Build compact change summary
          {
            echo "## Workflow Changes Detected"
            echo ""
            echo "Changes to GitHub Actions workflows in the last 8 hours."
            echo ""

            # Detailed commit information with links
            echo "### Commits"
            for commit in $COMMITS; do
              COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/$commit"
              COMMIT_MSG=$(git log -1 --pretty=format:'%s' $commit)
              COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an' $commit)
              COMMIT_TIME=$(git log -1 --pretty=format:'%ar' $commit)

              echo "- [\`${commit:0:7}\`]($COMMIT_URL) - $COMMIT_MSG ($COMMIT_AUTHOR, $COMMIT_TIME)"
            done
            echo ""

            # List changed files with stats
            echo "### Modified Files"
            git log --since="$SINCE" --stat --pretty=format: -- .github/workflows/ | grep -E '\.yml|\.yaml' | sort -u
            echo ""
            echo ""

            echo "---"
            echo ""
            echo "@claude Please review these workflow changes and update any affected documentation, API clients, or downstream systems in this repository that may be impacted."
            echo ""
            echo "**Repository:** ${{ github.repository }}"
            echo ""
            echo "**Links:**"
            echo "- [View workflow directory](${{ github.server_url }}/${{ github.repository }}/tree/main/.github/workflows)"
            echo "- [Recent commits](${{ github.server_url }}/${{ github.repository }}/commits/main/.github/workflows)"
            echo "- [This workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

          } > /tmp/issue-body.md

          # Store for next step
          cat /tmp/issue-body.md > $GITHUB_STEP_SUMMARY

      - name: Create issue in issue-dump
        if: steps.changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
        run: |
          TITLE="Workflow changes in ${{ github.repository }} ($(date -u '+%Y-%m-%d %H:%M UTC'))"

          gh issue create \
            --repo jamiew/issue-dump \
            --title "$TITLE" \
            --body-file /tmp/issue-body.md
