name: Crypto Prices

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  fetch-crypto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Claude Code with CoinGecko MCP
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_args: |
            --allowedTools "Read,Write,Bash(mkdir:*),Bash(curl:*)"
          prompt: |
            Fetch current cryptocurrency data for BTC, ETH, SOL, and HNT from the CoinGecko API.

            Use the CoinGecko API endpoint: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana,helium&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true&include_last_updated_at=true

            Parse the API response and store the results in data/crypto-prices.json with this structure:
            {
              "coins": {
                "BTC": { "name": "Bitcoin", "symbol": "BTC", "price": ..., "change_24h": ..., "market_cap": ..., "last_updated": ... },
                "ETH": { "name": "Ethereum", "symbol": "ETH", ... },
                "SOL": { "name": "Solana", "symbol": "SOL", ... },
                "HNT": { "name": "Helium", "symbol": "HNT", ... }
              },
              "last_updated": "ISO timestamp"
            }

            Make sure the data/ directory exists first. Use Bash with curl to fetch the data.

      - name: Commit crypto data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add data/crypto-prices.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update crypto prices - $(date -u +"%B %d, %Y")"
            git push
          fi
