name: Fetch HackerNews Top Story

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  fetch-and-create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch HN top story and comments
        id: fetch-hn
        run: |
          # Get top story ID
          TOP_STORY_ID=$(curl -s https://hacker-news.firebaseio.com/v0/topstories.json | jq '.[0]')
          echo "Top story ID: $TOP_STORY_ID"

          # Get story details
          STORY=$(curl -s "https://hacker-news.firebaseio.com/v0/item/${TOP_STORY_ID}.json")
          echo "$STORY" > hn_story.json

          TITLE=$(echo "$STORY" | jq -r '.title')
          URL=$(echo "$STORY" | jq -r '.url // empty')
          STORY_URL="https://news.ycombinator.com/item?id=${TOP_STORY_ID}"
          BY=$(echo "$STORY" | jq -r '.by')
          SCORE=$(echo "$STORY" | jq -r '.score')
          COMMENT_COUNT=$(echo "$STORY" | jq -r '.descendants // 0')

          # Get top 10 comment IDs
          COMMENT_IDS=$(echo "$STORY" | jq -r '.kids[0:10][]? // empty')

          # Fetch top comments
          COMMENTS=""
          for id in $COMMENT_IDS; do
            COMMENT=$(curl -s "https://hacker-news.firebaseio.com/v0/item/${id}.json")
            COMMENT_TEXT=$(echo "$COMMENT" | jq -r '.text // empty' | sed 's/<[^>]*>//g' | head -c 500)
            COMMENT_BY=$(echo "$COMMENT" | jq -r '.by // "unknown"')
            if [ -n "$COMMENT_TEXT" ]; then
              COMMENTS="${COMMENTS}\n\n**${COMMENT_BY}**: ${COMMENT_TEXT}..."
            fi
          done

          # Save for Claude to read
          cat > hn_context.md << EOF
          # HackerNews Top Story

          **Title**: ${TITLE}
          **Author**: ${BY}
          **Score**: ${SCORE}
          **Comments**: ${COMMENT_COUNT}
          **Story URL**: ${URL}
          **Discussion**: ${STORY_URL}

          ## Top Comments

          ${COMMENTS}
          EOF

          # Export for next step
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "story_url=$STORY_URL" >> $GITHUB_OUTPUT
          echo "score=$SCORE" >> $GITHUB_OUTPUT
          echo "comment_count=$COMMENT_COUNT" >> $GITHUB_OUTPUT

      - name: Claude analyzes and creates blog post issue
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_permissions: |
            {
              "Bash": "allow_all"
            }
          prompt: |
            A new top story from HackerNews needs a blog post!

            **Story Details:**
            - Title: ${{ steps.fetch-hn.outputs.title }}
            - URL: ${{ steps.fetch-hn.outputs.url }}
            - Discussion: ${{ steps.fetch-hn.outputs.story_url }}
            - Score: ${{ steps.fetch-hn.outputs.score }}
            - Comments: ${{ steps.fetch-hn.outputs.comment_count }}

            **Full context** (including top comments) is in `hn_context.md` - please read it.

            **Your Task:**

            1. Read `hn_context.md` to understand the full story + top comments
            2. Analyze what makes this story interesting/newsworthy
            3. Create a GitHub issue with:
               - Title: "Write blog post: [story title]"
               - Body should include:
                 - Link to original article
                 - Link to HN discussion
                 - 2-3 sentence summary of why it's interesting
                 - Key themes from top comments
                 - Suggested angle for the blog post
                 - Tag @claude at the end to trigger implementation

            Use `gh issue create` to make the issue.

            **Example issue body:**
            ```
            Write a blog post about [story title]

            **Original**: [url]
            **HN Discussion**: [story_url] ([score] points, [comments] comments)

            This story is trending because [reason]. Top comments discuss [themes].

            Suggested approach: [angle for blog post - analysis, tutorial, commentary, etc]

            @claude Please write a blog post about this, including:
            - Summary of the article
            - Key insights from HN discussion
            - Analysis/commentary
            - Save as blog/[slug].md with proper front matter
            ```

            Make it happen! 🚀
