name: Scheduled Page Update

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate webpage from data
        run: |
          mkdir -p dist
          node -e "
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('data.json', 'utf-8'));

          let headlinesHTML = '';
          if (data.nytimes_headlines && data.nytimes_headlines.length > 0) {
            headlinesHTML = '<h2>📰 NY Times Headlines</h2><ul>' +
              data.nytimes_headlines.map(h => \`<li>\${h}</li>\`).join('') +
              '</ul>';
          }

          let glifHTML = '';
          if (data.glif) {
            if (data.glif.featured_workflows && data.glif.featured_workflows.length > 0) {
              glifHTML += '<h2>🎨 Top Glif Workflows</h2><div class=\"glif-grid\">';
              data.glif.featured_workflows.forEach(w => {
                glifHTML += \`
                  <div class=\"glif-card\">
                    <h3><a href=\"\${w.url}\" target=\"_blank\">\${w.name}</a></h3>
                    <p>\${w.description || 'No description'}</p>
                    <small>by @\${w.creator}</small>
                  </div>
                \`;
              });
              glifHTML += '</div>';
            }

            if (data.glif.featured_agents && data.glif.featured_agents.length > 0) {
              glifHTML += '<h2>🤖 Top Glif Agents</h2><div class=\"glif-grid\">';
              data.glif.featured_agents.forEach(a => {
                glifHTML += \`
                  <div class=\"glif-card agent\">
                    <h3><a href=\"\${a.url}\" target=\"_blank\">\${a.name}</a></h3>
                    <p>\${a.description || 'No description'}</p>
                    <small>by @\${a.creator}</small>
                  </div>
                \`;
              });
              glifHTML += '</div>';
            }
          }

          const html = \`<!DOCTYPE html>
          <html lang=\"en\">
          <head>
            <meta charset=\"UTF-8\">
            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
            <title>Auto-Updated Data</title>
            <style>
              body {
                font-family: system-ui, -apple-system, sans-serif;
                max-width: 800px;
                margin: 40px auto;
                padding: 20px;
                line-height: 1.6;
              }
              pre {
                background: #f5f5f5;
                padding: 20px;
                border-radius: 8px;
                overflow-x: auto;
              }
              ul {
                background: #fff;
                padding: 20px 40px;
                border-left: 4px solid #0066cc;
              }
              li { margin: 10px 0; }
              .timestamp {
                color: #666;
                font-size: 0.9em;
              }
              .glif-grid {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
                gap: 20px;
                margin: 20px 0;
              }
              .glif-card {
                background: #fff;
                border: 2px solid #e0e0e0;
                border-radius: 12px;
                padding: 20px;
                transition: transform 0.2s, box-shadow 0.2s;
              }
              .glif-card:hover {
                transform: translateY(-4px);
                box-shadow: 0 4px 12px rgba(0,0,0,0.1);
              }
              .glif-card h3 {
                margin-top: 0;
                color: #333;
              }
              .glif-card a {
                color: #0066cc;
                text-decoration: none;
              }
              .glif-card a:hover {
                text-decoration: underline;
              }
              .glif-card p {
                color: #666;
                font-size: 0.9em;
                margin: 10px 0;
              }
              .glif-card small {
                color: #999;
              }
              .glif-card.agent {
                border-color: #9370db;
              }
            </style>
          </head>
          <body>
            <h1>🤖 Claude Auto-Updated Feed</h1>
            \${headlinesHTML}
            \${glifHTML}
            <h2>📊 Raw Data</h2>
            <pre>\${JSON.stringify(data, null, 2)}</pre>
            <p class=\"timestamp\">Last updated: \${new Date().toISOString()}</p>
          </body>
          </html>\`;
          fs.writeFileSync('dist/index.html', html);
          "

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
