name: TODO Worker

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours
  workflow_dispatch:
    inputs:
      force_item:
        description: 'Specific TODO item to work on (optional)'
        required: false
        type: string
      mode:
        description: 'Mode: implement, plan, or survey'
        required: false
        default: 'implement'
        type: choice
        options:
          - implement
          - plan
          - survey

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process-todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read TODO file
        id: read_todo
        run: |
          if [ ! -f TODO.md ]; then
            echo "No TODO.md file found"
            echo "has_todos=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Extract uncompleted TODO items
          TODOS=$(grep -E '^\s*- \[ \]' TODO.md || echo "")

          if [ -z "$TODOS" ]; then
            echo "No uncompleted TODO items found"
            echo "has_todos=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "has_todos=true" >> $GITHUB_OUTPUT

          # Count items
          COUNT=$(echo "$TODOS" | wc -l | tr -d ' ')
          echo "todo_count=$COUNT" >> $GITHUB_OUTPUT

          echo "Found $COUNT uncompleted TODO items"

      - name: Claude processes TODOs
        if: steps.read_todo.outputs.has_todos == 'true'
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_permissions: |
            {
              "Bash": {
                "enabled": true,
                "allowed_commands": ["gh issue*", "gh pr*"]
              }
            }
          prompt: |
            You are the TODO worker. Your job is to read TODO.md and implement items from the list.

            **Mode**: ${{ github.event.inputs.mode || 'implement' }}
            **Forced Item**: ${{ github.event.inputs.force_item || 'none - pick best item' }}

            ## Your Task

            1. **Read TODO.md** to see all pending items

            2. **Select one item to work on**:
               - If a specific item was requested, work on that
               - Otherwise, pick the best item based on:
                 * Items marked "High Priority" first
                 * Dependencies (does this unblock other items?)
                 * Feasibility (can you do this without external input?)
                 * Impact (how valuable is this?)
               - Skip items that require manual setup (like adding secrets)

            3. **Based on mode**:

               **implement mode** (default):
               - Actually implement the TODO item
               - Update TODO.md to mark it complete: `- [x] Item description`
               - Create a PR with your implementation
               - PR title: "✅ TODO: [item description]"

               **plan mode**:
               - Create a detailed implementation plan
               - Break down the item into subtasks
               - Identify any blockers or requirements
               - Add the plan as a comment in TODO.md or create an issue
               - Don't implement yet

               **survey mode**:
               - Review all TODO items
               - Prioritize and categorize them
               - Update TODO.md with better organization
               - Add difficulty/time estimates
               - Identify quick wins vs. complex projects

            4. **Quality guidelines**:
               - Follow existing code patterns
               - Test your changes (run workflows if applicable)
               - Update relevant documentation
               - Keep changes focused on one TODO item

            5. **If you can't complete an item**:
               - Add a note explaining why: `- [ ] Item (blocked: reason)`
               - Pick a different item
               - Or create an issue for investigation

            ## Important Notes

            - **One item at a time** - Don't try to do multiple TODOs in one PR
            - **Mark completed items** - Update TODO.md with [x] when done
            - **Create issues for blockers** - If something needs manual work
            - **Be autonomous** - Pick items you can complete without asking
            - **Leave difficult items** - If unsure, pick something simpler

            ## Context

            This is a self-improving automation system. You're helping it grow by:
            - Adding new data sources
            - Improving existing workflows
            - Enhancing the website
            - Building new features

            Current TODO count: ${{ steps.read_todo.outputs.todo_count }}

            Let's build something! 🚀
          pr_title: "✅ TODO Worker: Automated task implementation"
          pr_body: |
            This PR was created by the TODO worker workflow.

            Claude selected and implemented an item from TODO.md.

            **Mode**: ${{ github.event.inputs.mode || 'implement' }}
            **Run**: ${{ github.run_number }}

            Check the PR description for details on what was completed.
